version: 1

environment:
  grid_dimensions:
    width: 10
    height: 10
  obstacles_coordinates:
  - [0, 4]
  - [0, 11]
  - [0, 18]
  - [0, 24]

  - [1, 7]
  - [1, 9]
  - [1, 14]
  - [1, 22]

  - [2, 3]
  - [2, 6]
  - [2, 17]

  - [3, 5]
  - [3, 8]
  - [3, 12]
  - [3, 19]
  - [3, 27]

  - [4, 1]
  - [4, 10]
  - [4, 16]
  - [4, 21]
  - [4, 25]

  - [5, 6]
  - [5, 9]
  - [5, 18]
  - [5, 23]

  - [6, 3]
  - [6, 13]
  - [6, 17]
  - [6, 24]

  - [7, 8]
  - [7, 11]
  - [7, 19]

  - [8, 2]
  - [8, 6]
  - [8, 15]
  - [8, 28]

  - [9, 5]
  - [9, 9]
  - [9, 13]
  - [9, 21]

  - [10, 1]
  - [10, 7]
  - [10, 16]
  - [10, 25]

  - [11, 4]
  - [11, 10]
  - [11, 14]
  - [11, 22]

  - [12, 6]
  - [12, 12]
  - [12, 18]
  - [12, 26]

  - [13, 3]
  - [13, 9]
  - [13, 20]

  - [14, 5]
  - [14, 11]
  - [14, 17]
  - [14, 24]

  - [15, 2]
  - [15, 7]
  - [15, 13]
  - [15, 19]

  - [16, 4]
  - [16, 10]
  - [16, 21]

  - [17, 6]
  - [17, 12]
  - [17, 23]

  - [18, 8]
  - [18, 14]
  - [18, 19]
  - [18, 27]

  - [19, 3]
  - [19, 7]
  - [19, 16]
  - [19, 25]

  - [20, 5]
  - [20, 11]
  - [20, 18]

  - [21, 2]
  - [21, 9]
  - [21, 14]
  - [21, 22]

  - [22, 4]
  - [22, 10]
  - [22, 17]
  - [22, 26]

  - [23, 6]
  - [23, 13]
  - [23, 19]

  - [24, 3]
  - [24, 8]
  - [24, 21]

  - [25, 5]
  - [25, 12]
  - [25, 18]
  - [25, 27]

  - [26, 7]
  - [26, 15]
  - [26, 22]

  - [27, 10]
  - [27, 16]
  - [27, 24]

  - [28, 6]
  - [28, 13]
  - [28, 20]

  - [29, 9]
  - [29, 17]
  - [29, 26]

  # episode_time_limit: 250
  episode_time_limit: 50

agent:
  start_coordinates: [27, 3]
  goal_coordinates: [2, 26]
  velocity: 1
  visibility_radius: 5
  observation_stack_depth: 5

seekers:
  - start_coordinates:  [8, 20]
    velocity: 1
  - start_coordinates: [19, 12]
    velocity: 1
